# ENPM808W Spotify Project - Experimental
In this notebook, we tried to implement a Deep Neural Network to fit the data to genres, i.e. Genre Classification. This is an experimental notebook. This did not work out for us due to the non-covergence in the model caused by the vast dimensionality of the data.

In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [25]:
# Load datasets
data_by_genres = pd.read_csv('/content/drive/My Drive/Project Dataset/archive/data_by_genres.csv')
data_w_genres =  pd.read_csv('/content/drive/My Drive/Project Dataset/archive/data_w_genres.csv')

## Representing the dataset
We represent the dataset to understand how it is like

In [4]:
data_by_genres.head(10)

genres  acousticness  danceability  ...  popularity  key  mode
0             432hz      0.494780      0.299333  ...   52.166667    5     1
1                []      0.679245      0.521473  ...   21.682005    7     1
2        a cappella      0.621532      0.577017  ...   43.351819   11     1
3          abstract      0.359395      0.459500  ...   41.500000    1     1
4    abstract beats      0.353347      0.694400  ...   58.600000   10     0
5  abstract hip hop      0.205872      0.723132  ...   43.804971   11     1
6         accordeon      0.801333      0.626333  ...   28.666667    2     1
7         accordion      0.486208      0.640833  ...   15.208333    2     1
8        acid house      0.057002      0.684228  ...   44.566667   11     1
9         acid jazz      0.155414      0.714200  ...   44.033333    6     1

[10 rows x 14 columns]

In [5]:
data_w_genres.head()

artists  ...          genres
0                   "Cats" 1981 Original London Cast  ...  ['show tunes']
1                          "Cats" 1983 Broadway Cast  ...              []
2        "Fiddler On The Roof” Motion Picture Chorus  ...              []
3     "Fiddler On The Roof” Motion Picture Orchestra  ...              []
4  "Joseph And The Amazing Technicolor Dreamcoat"...  ...              []

[5 rows x 16 columns]

In [6]:
data_by_genres['genres'].value_counts()

greek contemporary classical    1
avant-garde metal               1
australian post-hardcore        1
dutch trance                    1
desi hip hop                    1
                               ..
israeli hip hop                 1
musikkorps                      1
hindustani instrumental         1
prepared piano                  1
chamber ensemble                1
Name: genres, Length: 2664, dtype: int64

In [7]:
# filter genres text by dropping []
df = data_by_genres.drop(data_by_genres[data_by_genres['genres'] == '[]'].index)
print(len(df['genres'].unique()))
print(len(df['genres']))

2663
2663


In [26]:
# Genre information rap and jazz
print(df[df['genres']=='rap'].value_counts())
print(df[df['genres']=='jazz'].value_counts())

genres  acousticness  danceability  duration_ms    energy    instrumentalness  liveness  loudness   speechiness  tempo      valence   popularity  key  mode
rap     0.150576      0.722337      240354.883486  0.666648  0.014343          0.20951   -7.347116  0.208261     116.14225  0.553055  52.575048   1    1       1
dtype: int64
genres  acousticness  danceability  duration_ms    energy    instrumentalness  liveness  loudness    speechiness  tempo       valence   popularity  key  mode
jazz    0.751593      0.505912      331072.141345  0.321045  0.374473          0.192582  -15.024195  0.059999     112.610828  0.483143  21.408293   5    1       1
dtype: int64


In [9]:
df.sort_values(by='popularity', ascending=False)

genres  acousticness  danceability  ...  popularity  key  mode
1118            guaracha      0.009030      0.745000  ...   82.000000    7     1
512              circuit      0.009030      0.745000  ...   82.000000    7     1
2141       russian dance      0.005610      0.653000  ...   79.000000    5     1
34             afroswing      0.367658      0.697292  ...   77.625000   11     0
2104       ritmo kombina      0.251333      0.845000  ...   77.333333    2     0
...                  ...           ...           ...  ...         ...  ...   ...
1786     norman ok indie      0.981000      0.506000  ...    0.000000    4     1
1406    jewish cantorial      0.982000      0.214000  ...    0.000000    2     0
1286  islamic recitation      0.988000      0.555000  ...    0.000000    2     0
1635    modern free jazz      0.961000      0.308000  ...    0.000000    2     1
1055           german oi      0.106143      0.281500  ...    0.000000   11     1

[2663 rows x 14 columns]

In [10]:
len(df['genres'].unique())

2663

In [11]:
df.head()

genres  acousticness  danceability  ...  popularity  key  mode
0             432hz      0.494780      0.299333  ...   52.166667    5     1
2        a cappella      0.621532      0.577017  ...   43.351819   11     1
3          abstract      0.359395      0.459500  ...   41.500000    1     1
4    abstract beats      0.353347      0.694400  ...   58.600000   10     0
5  abstract hip hop      0.205872      0.723132  ...   43.804971   11     1

[5 rows x 14 columns]

In [12]:
in_columns = [df.columns[i] for i in range(len(df.columns))]
print(in_columns)

['genres', 'acousticness', 'danceability', 'duration_ms', 'energy', 'instrumentalness', 'liveness', 'loudness', 'speechiness', 'tempo', 'valence', 'popularity', 'key', 'mode']


In [14]:
df_known = df.copy()

In [15]:
df_feature = df_known.drop('genres', axis=1)
df_target = df_known.drop(df_feature.columns, axis=1)
df_feature.head()
df_target.head(20)

genres
0              432hz
2         a cappella
3           abstract
4     abstract beats
5   abstract hip hop
6          accordeon
7          accordion
8         acid house
9          acid jazz
10         acid rock
11       acid trance
12        acousmatic
13    acoustic blues
14      acoustic pop
15     acoustic punk
16         adoracion
17   adult standards
18        adventista
19        afghan pop
20    african gospel

## Step 1: Pre-processing
Perform the preprocessing of the Output variable (Genre) by using One Hot Encoding

In [16]:
# Load pre-processing libraries
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

label_encode = LabelEncoder()
int_encode = label_encode.fit_transform(np.array(df_target).ravel())
Target = OneHotEncoder(sparse=False, drop='first').fit_transform(int_encode.reshape(-1,1))
print(Target)
inverted = label_encode.inverse_transform([np.argmax(Target[0, :])+1]) 
print(inverted)


[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
['a cappella']


In [27]:
# Load PyTorch library
import torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [18]:
# Dataset split to train and test
train_x_orig, test_x_orig, train_y_orig, test_y_orig = train_test_split(df_feature, Target, test_size=0.3, random_state=2)
train_x, train_y = train_x_orig.T, train_y_orig.T
test_x, test_y = test_x_orig.T, test_y_orig.T 
print("Train Size: X Features {}, Y Target {}".format(train_x.shape, train_y.shape))
print("Test Size: X Features {}, Y Target {}".format(test_x.shape, test_y.shape))

Train Size: X Features (13, 1864), Y Target (2662, 1864)
Test Size: X Features (13, 799), Y Target (2662, 799)


## Step 2: Implement a FCN 
implementing a Neural Network from scratch

In [32]:
class FCN(nn.Module):
  """
  Model class creates a Neural network
  param : Input Layer size, hidden layer 1 size, hidden layer 2 size, output layer size
  return : Activated output
  """
  def __init__(self, n_input, n_hidden1, n_hidden2, n_output):
    super(FCN,self).__init__()
    self.fc1 = nn.Linear(n_input, n_hidden1)
    self.fc2 = nn.Linear(n_hidden1, n_hidden2)
    self.fc3 = nn.Linear(n_hidden2, n_output)
    self.softmax = nn.Softmax(dim=1)
  
  def forward(self, x):
    x = torch.relu(self.fc1(x))
    x = torch.relu(self.fc2(x))
    x = self.fc3(x)
    # out = torch.softmax(x, dim=1)
    # out = self.softmax(x)
    out = torch.sigmoid(x)
    return out

In [33]:
# Setting the hyper-parameters of the model
learning_rate = 0.01
momentum = 0.9
weight_decay = 0.01
epochs = 1000

n_x = train_x.shape[0]
n_h1 = 13
n_h2 = 7
n_y = train_y.shape[0]

model = FCN(n_x, n_h1, n_h2, n_y) # Load model
loss_func = nn.MultiLabelSoftMarginLoss() #Defining the loss function: Muli Label loss
optim = torch.optim.SGD(model.parameters(), lr=learning_rate, momentum=momentum,weight_decay = weight_decay) #Create optimizer based on 'SGD'

In [34]:
# Convert Numpy to tensor
TrainX = torch.from_numpy(np.array(train_x))
TrainY = torch.from_numpy(np.array(train_y))
TestX = torch.from_numpy(np.array(test_x))
TestY = torch.from_numpy(np.array(test_y))

## Step 3: Train Model

In [35]:
# Train Model
model.train()

training_losses = []
for epoch in range(0,epochs):
  model_output = model(TrainX.T.float())
  loss = loss_func(model_output,TrainY.T.float())
  training_losses.append(loss)

  optim.zero_grad()
  loss.backward()
  optim.step()
  if epoch%100==0:
    print("Epoch: {}, Training Loss: {}".format(epoch,loss.item()))

print("Training Loss: "+str(training_losses[-1].float()))

Epoch: 0, Training Loss: 1.0099961757659912
Epoch: 100, Training Loss: 1.0095363855361938
Epoch: 200, Training Loss: 1.0093032121658325
Epoch: 300, Training Loss: 1.0093032121658325
Epoch: 400, Training Loss: 1.009303092956543
Epoch: 500, Training Loss: 1.0037118196487427
Epoch: 600, Training Loss: 1.0027821063995361
Epoch: 700, Training Loss: 1.0025495290756226
Epoch: 800, Training Loss: 1.002549409866333
Epoch: 900, Training Loss: 1.002083659172058
Training Loss: tensor(1.0014, grad_fn=<MeanBackward0>)


In [36]:
# Evaluate model and predictions
model.eval()
predictions = model(TestX.T.float())
print(predictions)
predictions[predictions > 0.18] = 1
predictions[predictions < 0.18] = 0
print(predictions)

tensor([[1.0000e+00, 1.0000e+00, 4.1658e-10,  ..., 0.0000e+00, 1.0000e+00,
         1.0000e+00],
        [1.0000e+00, 1.0000e+00, 3.8575e-08,  ..., 0.0000e+00, 1.0000e+00,
         1.0000e+00],
        [1.0000e+00, 1.0000e+00, 1.0976e-13,  ..., 0.0000e+00, 1.0000e+00,
         1.0000e+00],
        ...,
        [1.0000e+00, 1.0000e+00, 1.7103e-08,  ..., 0.0000e+00, 1.0000e+00,
         1.0000e+00],
        [1.0000e+00, 1.0000e+00, 5.9609e-11,  ..., 0.0000e+00, 1.0000e+00,
         1.0000e+00],
        [1.0000e+00, 1.0000e+00, 9.2356e-11,  ..., 0.0000e+00, 1.0000e+00,
         1.0000e+00]], grad_fn=<SigmoidBackward>)
tensor([[1., 1., 0.,  ..., 0., 1., 1.],
        [1., 1., 0.,  ..., 0., 1., 1.],
        [1., 1., 0.,  ..., 0., 1., 1.],
        ...,
        [1., 1., 0.,  ..., 0., 1., 1.],
        [1., 1., 0.,  ..., 0., 1., 1.],
        [1., 1., 0.,  ..., 0., 1., 1.]], grad_fn=<IndexPutBackward>)


In [37]:
# Evaluation using confusion matrix
# The model overfits and does not converge
y_test = torch.max(TestY.T, 1)[1].detach().numpy()
y_pred = torch.max(predictions, 1)[1].detach().numpy()
print(y_test.shape)
print(y_pred.shape)
confusion_matrix(y_pred, y_test)

(799,)
(799,)


array([[0, 1, 1, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [38]:
pip freeze > requirements.txt